# Generated by Django 5.1.4 on 2025-01-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0002_alter_painting_photo_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='category',
            field=models.CharField(choices=[('Bookmark', 'Bookmark'), ('Landscape', 'Landscape'), ('Portrait', 'Portrait'), ('Sketch', 'Sketch')], default='Bookmark', max_length=10),
        ),
    ]
