# Generated by Django 5.1.4 on 2025-01-17 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0003_alter_painting_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='dimensions',
        ),
    ]
