# Generated by Django 5.1.4 on 2025-01-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0005_cartitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='delivery',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=10),
        ),
    ]
