# Generated by Django 5.1.4 on 2025-01-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0006_cartitem_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='delivery',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10),
        ),
    ]
