# Generated by Django 5.1.4 on 2025-02-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0007_alter_cartitem_delivery_alter_cartitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('unpaid(COD)', 'Unpaid(COD)'), ('paid', 'Paid')], default='unpaid', max_length=12),
        ),
    ]
