# Generated by Django 5.1.4 on 2025-02-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_userprofile_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_admin',
        ),
    ]
